# -*- coding: utf-8 -*-
"""Smartbridge_project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mAAyhI2rXnWsZNKj7SgcVQkfPOFPM2i6
"""

!pip install kaggle tensorflow matplotlib seaborn

import kagglehub
import os
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf

from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.models import Sequential, Model
from tensorflow.keras.layers import Dense, Conv2D, MaxPooling2D, Flatten, Dropout, GlobalAveragePooling2D
from tensorflow.keras.applications import MobileNetV2, EfficientNetB0

path = kagglehub.dataset_download("iarunava/cell-images-for-detecting-malaria")

print("Dataset downloaded at:", path)

os.listdir(path)

import random
import os
import shutil

dataset_path = os.path.join(path, "cell_images", "cell_images")

print(os.listdir(dataset_path))
parasitized_path = os.path.join(dataset_path, "Parasitized")
uninfected_path = os.path.join(dataset_path, "Uninfected")
import shutil

subset_path = "/content/malaria_subset"

if os.path.exists(subset_path):
    shutil.rmtree(subset_path)



os.makedirs(subset_path + "/Parasitized", exist_ok=True)
os.makedirs(subset_path + "/Uninfected", exist_ok=True)

parasitized_images = os.listdir(parasitized_path)
uninfected_images = os.listdir(uninfected_path)

parasitized_sample = random.sample(parasitized_images, 499)
uninfected_sample = random.sample(uninfected_images, 499)

for img in parasitized_sample:
    shutil.copy(
        os.path.join(parasitized_path, img),
        os.path.join(subset_path, "Parasitized", img)
    )

for img in uninfected_sample:
    shutil.copy(
        os.path.join(uninfected_path, img),
        os.path.join(subset_path, "Uninfected", img)
    )

print("Uninfected:", len(os.listdir(subset_path + "/Uninfected")))
print("Parasitized:", len(os.listdir(subset_path + "/Parasitized")))

BATCH_SIZE = 32
IMG_SIZE = (128,128)

datagen = ImageDataGenerator(
    rescale=1./255,
    validation_split=0.2
)

train_gen = datagen.flow_from_directory(
    subset_path,
    target_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    class_mode='binary',
    subset='training',
    shuffle=False
)

val_gen = datagen.flow_from_directory(
    subset_path,
    target_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    class_mode='binary',
    subset='validation',
    shuffle=False
)

def create_custom_cnn():

    model = Sequential([
        Conv2D(32,(3,3),activation='relu',input_shape=(128,128,3)),
        MaxPooling2D(2,2),

        Conv2D(64,(3,3),activation='relu'),
        MaxPooling2D(2,2),

        Conv2D(128,(3,3),activation='relu'),
        MaxPooling2D(2,2),

        Flatten(),
        Dense(128,activation='relu'),
        Dropout(0.5),
        Dense(1,activation='sigmoid')
    ])

    model.compile(
        optimizer='adam',
        loss='binary_crossentropy',
        metrics=['accuracy']
    )

    return model

def create_mobilenet():

    base_model = MobileNetV2(
        weights='imagenet',
        include_top=False,
        input_shape=(128,128,3)
    )

    x = base_model.output
    x = GlobalAveragePooling2D()(x)
    x = Dense(256,activation='relu')(x)
    x = Dropout(0.5)(x)
    output = Dense(1,activation='sigmoid')(x)

    model = Model(inputs=base_model.input,outputs=output)

    model.compile(
        optimizer='adam',
        loss='binary_crossentropy',
        metrics=['accuracy']
    )

    return model

def create_efficientnet():

    base_model = EfficientNetB0(
        weights='imagenet',
        include_top=False,
        input_shape=(128,128,3)
    )

    x = base_model.output
    x = GlobalAveragePooling2D()(x)
    x = Dense(256,activation='relu')(x)
    x = Dropout(0.5)(x)
    output = Dense(1,activation='sigmoid')(x)

    model = Model(inputs=base_model.input,outputs=output)

    model.compile(
        optimizer='adam',
        loss='binary_crossentropy',
        metrics=['accuracy']
    )

    return model

custom_model = create_custom_cnn()
mobilenet_model = create_mobilenet()
efficientnet_model = create_efficientnet()

history_custom = custom_model.fit(
    train_gen,
    validation_data=val_gen,
    epochs=40
)

history_mobile = mobilenet_model.fit(
    train_gen,
    validation_data=val_gen,
    epochs=40
)

history_efficient = efficientnet_model.fit(
    train_gen,
    validation_data=val_gen,
    epochs=40
)

import matplotlib.pyplot as plt

def plot_training(history, title):

    acc = history.history['accuracy']
    val_acc = history.history['val_accuracy']

    loss = history.history['loss']
    val_loss = history.history['val_loss']

    epochs = range(len(acc))

    plt.figure(figsize=(12,4))

    # Accuracy
    plt.subplot(1,2,1)
    plt.plot(epochs, acc, label="Train Accuracy")
    plt.plot(epochs, val_acc, label="Validation Accuracy")
    plt.title(title + " Accuracy")
    plt.xlabel("Epoch")
    plt.ylabel("Accuracy")
    plt.legend()

    # Loss
    plt.subplot(1,2,2)
    plt.plot(epochs, loss, label="Train Loss")
    plt.plot(epochs, val_loss, label="Validation Loss")
    plt.title(title + " Loss")
    plt.xlabel("Epoch")
    plt.ylabel("Loss")
    plt.legend()

    plt.show()

plot_training(history_custom, "Custom CNN")
plot_training(history_mobile, "MobileNetV2")
plot_training(history_efficient, "EfficientNetB0")

from sklearn.metrics import classification_report
import numpy as np

val_gen.reset()
y_true = val_gen.classes

y_pred_custom = custom_model.predict(val_gen)
y_pred_custom = (y_pred_custom > 0.5).astype(int)

print("CUSTOM CNN CLASSIFICATION REPORT")
print(classification_report(
    y_true,
    y_pred_custom,
    target_names=["Parasitized","Uninfected"]
))

y_pred_mobile = mobilenet_model.predict(val_gen)
y_pred_mobile = (y_pred_mobile > 0.5).astype(int)

print("MOBILENETV2 CLASSIFICATION REPORT")
print(classification_report(
    y_true,
    y_pred_mobile,
    target_names=["Parasitized","Uninfected"]
))

y_pred_efficient = efficientnet_model.predict(val_gen)
y_pred_efficient = (y_pred_efficient > 0.5).astype(int)

print("EFFICIENTNETB0 CLASSIFICATION REPORT")
print(classification_report(
    y_true,
    y_pred_efficient,
    target_names=["Parasitized","Uninfected"]
))

custom_model.save("custom_cnn_model1.h5")
mobilenet_model.save("mobilenet_model1.h5")
efficientnet_model.save("efficientnet_model1.h5")

from google.colab import files

files.download("custom_cnn_model1.h5")
files.download("mobilenet_model1.h5")
files.download("efficientnet_model1.h5")

from sklearn.metrics import confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

cm = confusion_matrix(y_true, y_pred_mobile)

plt.figure(figsize=(5,4))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues",
            xticklabels=["Parasitized","Uninfected"],
            yticklabels=["Parasitized","Uninfected"])
plt.title("MobileNetV2 Confusion Matrix")
plt.ylabel("Actual")
plt.xlabel("Predicted")
plt.show()

